### PR TITLE
Use ResolvedUrl type in loader.

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md not updated, internal change

### CODE REVIEW

**Comment by rictic** [comment]
Also fixed a legit bug from https://github.com/Polymer/polymer-analyzer/pull/734

**Comment by usergenic** [comment]
Thanks for updating to skip the back-reference import!

**Comment by usergenic** [comment]
While I feel like the html-script-back-reference check should be in the filtering as opposed to in the createPushEntryFromImport function, that's subjective enough of a feels that this is still LGTM

**Comment by rictic** [comment]
+1, moved the filtering into one place.

**Pull request merged**
