### PR TITLE
Mention whitelisting 3rd party services

### PR DESCRIPTION
**Pull request by robdodson**

### CODE REVIEW

**Comment by robdodson** [comment]
k I think this is read. @fks PTAL

**Comment by FredKSchott** [comment]
looks good, can you move down the section on 'sw-precache' to be immediately above this? Since they're related they'll be more helpful together. 

Either section could also be re-written to include a more explicit mention to "see [sw-preache](https://github.com/GoogleChrome/sw-precache#options-parameter) for a list of all supported options" (this should have probably been included from the beginning).

**Comment by robdodson** [comment]
Updated PTAL

**Comment by FredKSchott** [comment]
Awesome, LGTM!

**Pull request merged**
