### PR TITLE
[v0.7.0] RELEASE

### PR DESCRIPTION
**Pull request by FredKSchott**
- [x] Changelog has been updated

/cc @justinfagnani @web-padawan

### CODE REVIEW

**Comment by FredKSchott** [comment]
Will wait for new bundler (https://github.com/Polymer/polymer-build/pull/108) & hopefully missing files fix (https://github.com/Polymer/polymer-build/pull/111)

**Comment by web-padawan** [comment]
Amazing to have a new bundler soon! But will you land a `0.7.0-alpha.1` release at first like it was with `0.6.0`? 
I'm looking forward to an opportunity to test the `polymer-bundler` on our project, especially because of stack trace issues with `vulcnize`.

**Comment by FredKSchott** [comment]
Yea we'll see how everything lands timing-wise. I'd like to get what's ready now and #110 out as `0.7.0` before we start a new `0.18.0.pre-1` branch for the new bundler.

**Comment by FredKSchott** [comment]
Bundler is still being worked on, so lets not block a new release for that. 

We were able to get the missing files fix in just now, so lets call this a `v0.7.0` release and then focus on new new bundler and splitting/rejoining fix for `v0.8.0`, which will almost definitely require a few `pre` releases to kick the tires.

**Pull request merged**
